---
title: "Bike Sharing Analysis, Time Series Final Project"
author: "Derek Rogers and Sakava Kiv"
date: "2024-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tswge)
library(PolynomF)
library(tidyverse)
library(GGally)
library(astsa)
library(vars)
library(nnfor)
library(dplyr)
```

```{r}
# Set the working directory to the specified path
setwd("C:/SMU MS Data Science/TimeSeries/FinalProject/BikeSharingTimeSeriesAnalysis")

# Check to confirm that the working directory has been set correctly
getwd()
```

```{r}
# The chosen data set is the bike_sharing_dataset.csv from kaggle: https://www.kaggle.com/datasets/juliajemals/bike-sharing-washington-dc
# The chosen response variable is total_cust
# Being able to model and predict total_cust can help entities directly involved or adjacent to bike sharing better understand and predict the varying demand to avoid oversupply or shortages. Forecasting future demand can help plan bike maintance as heavily used bikes break down more often. This information can help inform business decisions, setting prices, and creating efective advertisements. 

BikeSharing = read.csv("bike_sharing_dataset.csv", header = TRUE)
BikeSharing_train = data.frame(TotalCust = ts(BikeSharing$total_cust))

head(BikeSharing)
nrow(BikeSharing)

# There are 4 consecutive missing values
which(is.na(BikeSharing$total_cust))
```

```{r}
# Impute the 4 consecutive missing values with the average of the value before and after the missing values

# Calculate the average of the values at positions 1848 and 1853
average_value = mean(c(BikeSharing$total_cust[1848], BikeSharing$total_cust[1853]), na.rm = TRUE)
average_value

# Assign the average value to the missing positions 1849, 1850, 1851, and 1852
BikeSharing$total_cust[1849:1852] = average_value

# Optionally, you can verify the imputation by checking the values at these positions
BikeSharing$total_cust[1848:1853]

# Plot around where the imputed values are
plot(BikeSharing$total_cust[1838:1863], type = "l")
```

```{r}
# Plot the full dataset

# The realization plot shows strong periodic trends, wandering behavior, and variance that changes over time.

# We see slowly dampening autocorrelation with weak and an irregular length periodic behavior.

# There is a peak at zero in the parzen frequency window.
# The parzen window also shows a peak around 0.15, which is a period of 1/0.15 = 6.666. 
#   B/c this data is collected daily, there evidence to suggest a weekly trend.
#   We can hypothesize total_cust could have a greater total_cust on the weekends when all other variables are held constant. 
plotts.sample.wge(BikeSharing$total_cust, arlimits = TRUE)
```

```{r}
# The CCF plot shows a log of 1 for precipitation. This makes sense a we might expect less people to rent a bike the day after it rains.
ccf(BikeSharing$precip, BikeSharing$total_cust)
```

```{r}
BikeSharing$precip_L1 = dplyr::lag(BikeSharing$precip, 1)
BikeSharing$precip_L1[is.na(BikeSharing$precip_L1)] = median(BikeSharing$precip_L1, na.rm = TRUE)
head(BikeSharing)
```

```{r}
# Transform data based off of Sakavas analysis
b7 = artrans.wge(BikeSharing$total_cust, phi.tr = c(rep(0, 6), 1))
b7
b365 = artrans.wge(BikeSharing$total_cust, phi.tr = c(rep(0, 364), 1))
b365
b365_7 = artrans.wge(b365, phi.tr = c(rep(0, 6), 1))
b365_7

plotts.sample.wge(b365_7, arlimits = TRUE)
```

```{r}
head(b365_7)
```

# ARMA/ARIMA Modle

```{r}
fit_365_7 = est.ar.wge(b365_7, p = 8)

preds_arma_7 = fore.arma.wge(BikeSharing$total_cust,
    phi = fit_365_7$phi, n.ahead = 7,
    lastn = TRUE, limits = FALSE)
```

```{r}
preds_arma_182 = fore.arma.wge(BikeSharing$total_cust,
    phi = fit_365_7$phi, n.ahead = 182,
    lastn = TRUE, limits = FALSE)
```

```{r}
ASE_7 = mean((tail(BikeSharing$total_cust, 7) - preds_arma_7$f)^2)
ASE_7

ASE_182 = mean((tail(BikeSharing$total_cust, 182) - preds_arma_182$f)^2)
ASE_182
```

```{r}
plotts.sample.wge(fit_365_7$res, arlimits = TRUE)
```

```{r}
roll.win.rmse.wge(b365_7, phi = fit_365_7$phi, horizon = 7)
roll.win.rmse.wge(b365_7, phi = fit_365_7$phi, horizon = 182)
```

# VAR Model

```{r}
head(BikeSharing)
```

```{r}
colnames(BikeSharing)
which(is.na(BikeSharing$temp_min))
```

```{r}
no_missing_values = apply(BikeSharing, 2, function(x) all(complete.cases(x)))
columns_no_missing = names(BikeSharing)[no_missing_values]

# All columns
colnames(BikeSharing)
# Columns with no missing values
print(columns_no_missing)
# date, total_cust, temp_min, temp_max, temp_observ, precip, wind
```

```{r}
# Select columns with no missing values excluding 'date' and 'precip_L1'
variables = c("total_cust", "temp_min", "temp_max", "temp_observ", "precip", "wind")
BikeSharingSelected = BikeSharing[variables]

# Leave out the last 182 values for the ASE calculation
BikeSharingSmall = head(BikeSharingSelected, -182)

# Prepare the data for the VAR model
BikeSharingDF = data.frame(BikeSharingSmall[,-1]) # Exclude 'total_cust' for independent variables
TotalCust = BikeSharingSmall$total_cust
```

```{r}
# Double check we have all the dependent variables correctly saved to the dataframe
head(BikeSharingDF)
```

```{r}
# Create the VAR model
VAR_BikeSharing = VAR(cbind(TotalCust, BikeSharingDF), lag.max = 5, type = "both")

# Prediction
pred_VAR_7 = predict(VAR_BikeSharing, n.ahead = 7)
pred_VAR_182 = predict(VAR_BikeSharing, n.ahead = 182)
```

```{r}
# Plot the actual vs predicted 'total_cust'
plot(BikeSharing$total_cust, type = "l", main = "Total Customers: Actual vs Predicted", xlab = "Time", ylab = "Total Customers", xlim = c(2800, nrow(BikeSharing)))
lines((nrow(BikeSharing) - 6):nrow(BikeSharing), pred_VAR_7$fcst$TotalCust[,1], col = "red")
```

```{r}
# Plot the actual vs predicted 'total_cust' zoomed in on the last 1/6th of the timeline
plot(BikeSharing$total_cust, type = "l", main = "Total Customers: Actual vs Predicted", xlab = "Time", ylab = "Total Customers", xlim = c(2500, nrow(BikeSharing)))
lines((nrow(BikeSharing) - 181):nrow(BikeSharing), pred_VAR_182$fcst$TotalCust[,1], col = "red")
```

```{r}
# Calculate the Average Squared Error (ASE) for the prediction
ASE_VAR_7 = mean((tail(BikeSharing$total_cust, 7) - pred_VAR_7$fcst$TotalCust[,1])^2)
print(ASE_VAR_7)

ASE_VAR_182 = mean((tail(BikeSharing$total_cust, 182) - pred_VAR_182$fcst$TotalCust[,1])^2)
print(ASE_VAR_182)
```

# MLP Model
```{r}
# Exclude the first 2,300 values from BikeSharingSmall and BikeSharingDF
BikeSharingSmallAdjusted = BikeSharingSmall[-(1:2300), ]
BikeSharingDFAdjusted = BikeSharingDF[-(1:2300), ]
fit_mlp = mlp(ts(BikeSharingSmallAdjusted$total_cust), reps = 7, comb = "median", xreg = BikeSharingDFAdjusted)

plot(fit_mlp)
```

```{r}
fore_mlp_182 = forecast(fit_mlp, h = 182, xreg = BikeSharingSelected[-(1:2300), -1])
fore_mlp_7 = forecast(fit_mlp, h = 7, xreg = BikeSharingSelected[-(1:2300), -1])
```

```{r}
plot(fore_mlp_182)
```

```{r}
# Plot the actual 'total_cust' values
plot(BikeSharing$total_cust, type = "l", main = "Total Customers: Actual vs Predicted", xlab = "Time", ylab = "Total Customers", xlim = c(2500, nrow(BikeSharing)))

# Add the MLP forecasted 'total_cust' values
lines((nrow(BikeSharing) - 181):nrow(BikeSharing), fore_mlp_182$mean, col = "red")
```

```{r}
# Plot the actual 'total_cust' values
plot(BikeSharing$total_cust, type = "l", main = "Total Customers: Actual vs Predicted", xlab = "Time", ylab = "Total Customers", xlim = c(2800, nrow(BikeSharing)))

# Add the MLP forecasted 'total_cust' values
lines((nrow(BikeSharing) - 6):nrow(BikeSharing), fore_mlp_7$mean, col = "red")
```

```{r}
ASE_mlp_182 = mean((tail(BikeSharing$total_cust, 182) - fore_mlp_182$mean)^2)
print(ASE_mlp_182)

ASE_mlp_7 = mean((tail(BikeSharing$total_cust, 7) - fore_mlp_7$mean)^2)
print(ASE_mlp_7)
```

# Ensemble

```{r}
#Ensemble
ensemble_182 = (preds_arma_182$f + pred_VAR_182$fcst$TotalCust[, 1] + fore_mlp_182$mean) / 3

#Plot
plot(BikeSharing$total_cust, type = "l", xlim = c(2500, nrow(BikeSharing)), ylab = "Total Customers: Actual vs Predicted", main = "26 Week Customer Forecast")
lines((nrow(BikeSharing) - 181):nrow(BikeSharing), ensemble_182, type = "l", col = "red")

ASE_ensemble_182 = mean((tail(BikeSharing$total_cust, 182) - ensemble_182)^2)
ASE_ensemble_182
```

```{r}
#Ensemble
ensemble_7 = (preds_arma_7$f + pred_VAR_7$fcst$TotalCust[, 1] + fore_mlp_7$mean) / 3

#Plot
plot(BikeSharing$total_cust, type = "l", xlim = c(2800, nrow(BikeSharing)), ylab = "Total Customers: Actual vs Predicted", main = "1 Week Customer Forecast")
lines((nrow(BikeSharing) - 6):nrow(BikeSharing), ensemble_7, type = "l", col = "red")

ASE_ensemble_7 = mean((tail(BikeSharing$total_cust, 7) - ensemble_7)^2)
ASE_ensemble_7
```

```{r}

```